### ISSUE TITLE
ahorrate un comando

### ISSUE THREAD

**Issue by SoraSilver27** [Arcemist/ProyectoUTU#8]
composer install
cp .env.example .env
php artisan key:generate
php artisan migrate
php artisan db:seed // te la podés ahorrar escribiendo --seed en el anterior comando
npm install
npm run build

**Comment by Arcemist** [comment]
De hecho no me conviene ahorrarme ese commando porque es mejor tenerlo en comandos separados para que si algo da error se ve bien que es lo que dio el error.

**Comment by Arcemist** [comment]
Y pa poner una issue es mejor poner el cambio que estas haciendo al inicio en vez de ponerlo en un commentario
